version: '3.9'

services:
  app:
    image: vaadin-app:local
    container_name: vaadin-app
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hr-admin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: daster
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: hr-admin
    environment:
      POSTGRES_DB: hr-admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: