version: '3.9'

services:
  app:
    image: ghcr.io/dima1212qqq/hradmin:latest
    container_name: vaadin-app
    ports:
      - "80:80"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hr-admin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
#      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_USERNAME: dova@dovakuni.ru
      PORT: ${PORT}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16
    container_name: hr-admin
    environment:
      POSTGRES_DB: hr-admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  default:
    name: hr-admin-network
    driver: bridge