version: '3.9'

services:
  app:
    build: .
    container_name: vaadin-app
    ports:
      - "8080:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/hr-admin
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: daster
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    container_name: hr-admin
    environment:
      POSTGRES_DB: hr-admin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: daster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  default:
    name: my-network
    driver: bridge