name: Deploy Spring Boot to VPS

on:
  push:
    branches: [ "main" ]

env:
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
  MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
  PORT: ${{ secrets.PORT }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package -Pproduction

    - name: Verify JAR file
      run: ls -l target/hr-admin-*.jar

    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        source: "target/hr-admin-*.jar"
        target: "/opt/hr-admin/"
        overwrite: true
        strip_components: 1

    - name: Restart application
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          sudo systemctl stop hr-admin.service || true
          sudo find /opt/hr-admin/ -name "*.jar" -exec mv {} /opt/hr-admin/hr-admin.jar \;
          sudo chown ubuntu:ubuntu /opt/hr-admin/hr-admin.jar
          sudo systemctl daemon-reload
          sudo systemctl start hr-admin.service
