name: Deploy Spring Boot to VPS

on:
  push:
    branches: [ "main" ]

env:
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -Pproduction

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: hr-admin
        path: target/*.jar

    - name: Deploy to VPS
      uses: appleboy/scp-action@v0.1.3
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        source: "target/*.jar"
        target: "/opt/hr-admin/"
        
    - name: Restart application
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          sudo systemctl stop hr-admin.service || true
          sudo cp /opt/hr-admin/*.jar /opt/hr-admin/hr-admin.jar
          sudo systemctl start hr-admin.service
